website:
  title: "Discovering Statistics"                                # Your name
  description: "The adventure begins ..."   # A brief slogan (optional)
  image: images/ds6_cover_small.jpg
  favicon: images/ds_favicon.png
  navbar:  
    pinned: true
    logo: /images/ds_favicon.png
    left:
      - text: "About me"
        href: https://profandyfield.com
      - text: "The discoverse"
        href: https://profandyfield.com/discoverse
      - text: "Statistics Hell-p"
        menu:
          - href: pages/postverta.qmd
          - href: pages/antevorta.qmd
          - href: pages/porus.qmd
          - href: pages/egestes.qmd
          - href: pages/veritas.qmd
      - text: "Shop"
        href: https://discstat.myspreadshop.co.uk/
    right:
      - icon: github
        href: https://github.com/profandyfield
      - icon: r-circle-fill
        href: https://www.discovr.rocks
      - text: "{{< fa brands x-twitter >}}"
        href: https://twitter.com/profandyfield
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/profandyfield.bsky.social
      - icon: linkedin
        href: https://www.linkedin.com/in/profandyfield/
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">&#169; 2024 Andy Field CC BY-SA 4.0</span>
  google-analytics: "G-H6MJK8MHBB"

project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    browser: true
    watch-inputs: true
    navigate: true
  render:
    - "*.qmd"
    - "!dev/"
execute:
  freeze: true
  echo: false
  warnings: false
  message: false
format:
  html:
    fontsize: 1.1em
    theme:
      light: [pulse, html/styles.scss]
      dark: [darkly, html/styles.scss]
    toc: true
    toc_depth: 2
    toc-location: left
    toc-title: Map
    toc_float: true
    code-link: true
    highlight-style: ayu
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true



